# Generated by Django 5.1.3 on 2024-11-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_alter_room_options_room_host_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
